/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.klijent;

import communication.Request;
import controller.ControllerClient;
import domain.FizickoLice;
import domain.Klijent;
import domain.PravnoLice;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import operations.Operations;
import view.components.ModelTabeleKlijenti;

/**
 *
 * @author milos
 */
public class PretrazivanjeKlijentaForma extends javax.swing.JDialog {

    /**
     * Creates new form KreiranjeOtpremniceForma
     */
    public PretrazivanjeKlijentaForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        btnPrikazi = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKlijenti = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText(" Unesite ime ili naziv:");

        btnPrikazi.setText("Prikazi");
        btnPrikazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        jButton1.setText("Obrisi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblKlijenti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblKlijenti);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPrikazi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrikazi)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzmeni)
                    .addComponent(jButton1))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(tblKlijenti.getSelectedRow()!=-1){
            try {
                ModelTabeleKlijenti mtk = (ModelTabeleKlijenti) tblKlijenti.getModel();
                Request r = new Request();
                r.setOperation(Operations.OBRISI_KLIJENTA);
                r.setArgument(mtk.getKlijent(tblKlijenti.getSelectedRow()));
                ControllerClient.getInstance().deleteKlijent(r);
                mtk.izbrisi(tblKlijenti.getSelectedRow());
                JOptionPane.showMessageDialog(this, "Klijent je izbrisan");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Greska");
                //Logger.getLogger(PretrazivanjeKlijentaForma.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        System.out.println(tblKlijenti.getSelectedRow());
        if(tblKlijenti.getSelectedRow()!=-1){
            ModelTabeleKlijenti mtk = (ModelTabeleKlijenti) tblKlijenti.getModel();
            Object klijent = mtk.getKlijent(tblKlijenti.getSelectedRow());
            if(klijent instanceof FizickoLice){
                IzmenaFizickoLice ifl = new IzmenaFizickoLice(null, true, klijent);
                ifl.setVisible(true);
            }
            else{
                IzmenaPravnoLice ipl = new IzmenaPravnoLice(null, true, klijent);
                ipl.setVisible(true);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Izaberite klijenta");
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnPrikaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziActionPerformed
        try {
            if(txtIme.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Popunite sva polja");
            }
            else{
                String kriterijum = txtIme.getText();
                ArrayList<Object> lista1 = ControllerClient.getInstance().searchFizickaLica(kriterijum);
                ArrayList<Object> lista2 = ControllerClient.getInstance().searchPravnaLica(kriterijum);
                for (Object o : lista2) {
                    lista1.add(o);
                }
                ModelTabeleKlijenti mtk = (ModelTabeleKlijenti) tblKlijenti.getModel();
                mtk.setLista(lista1);
                if(lista1.size()==0){
                    JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje klijente po zadatoj vrednosti");
                }
            }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska");
            //Logger.getLogger(PretrazivanjeKlijentaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPrikaziActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnPrikazi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblKlijenti;
    private javax.swing.JTextField txtIme;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        try {
            ArrayList<FizickoLice> fLica = ControllerClient.getInstance().getFizickaLica();
            ArrayList<PravnoLice> pLica = ControllerClient.getInstance().getPravnaLica();
            ArrayList<Object> lista =  new ArrayList<>();
            for (FizickoLice fl : fLica) {
                lista.add(fl);
            }
            for (PravnoLice pl : pLica) {
                lista.add(pl);
            }
            ModelTabeleKlijenti mtk = new ModelTabeleKlijenti(lista);
            tblKlijenti.setModel(mtk);
            JOptionPane.showMessageDialog(this, "Ucitana je lista klijenata");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska pri ucitavanju podataka");
            //Logger.getLogger(PretrazivanjeKlijentaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
