/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.otpremnica;

import controller.ControllerClient;
import domain.FizickoLice;
import domain.Otpremnica;
import domain.PravnoLice;
import domain.Roba;
import domain.StavkeOtpremnice;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import view.components.ModelTabeleStavke;

/**
 *
 * @author milos
 */
public class IzmenaOtpremniceForma extends javax.swing.JDialog {
    Otpremnica otpremnica;
    /**
     * Creates new form IzmenaOtpremniceTest
     */
    public IzmenaOtpremniceForma(java.awt.Frame parent, boolean modal, Otpremnica otpremnica) {
        super(parent, modal);
        initComponents();
        this.otpremnica = otpremnica;
        
        srediFormu();
        txtOdrediste.setText(otpremnica.getOdrediste());
        ModelTabeleStavke mts = new ModelTabeleStavke(otpremnica.getStavke());
        tblStavke.setModel(mts);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbRoba = new javax.swing.JComboBox();
        cmbJedinica = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtKolicina = new javax.swing.JTextField();
        btnDodaj = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        txtOdrediste = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblKlijent = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Klijent:");

        jLabel2.setText("Roba:");

        cmbRoba.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbJedinica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Jedinica mere:");

        jLabel4.setText("Kolicina:");

        btnDodaj.setText("Dodaj stavku otpremnice");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavke);

        jButton3.setText("Izbrisi stavku");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Sacuvaj izmene");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Odrediste:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(lblKlijent, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbRoba, 0, 103, Short.MAX_VALUE)
                            .addComponent(cmbJedinica, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtKolicina))
                        .addGap(36, 36, 36)
                        .addComponent(btnDodaj)
                        .addGap(55, 55, 55))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel5)
                                .addGap(24, 24, 24)
                                .addComponent(txtOdrediste, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblKlijent, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbRoba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbJedinica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtOdrediste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        if(provera()){
            StavkeOtpremnice so = new StavkeOtpremnice();
            so.setOtpremnica(otpremnica);
            so.setJedinicaMere((String) cmbJedinica.getSelectedItem());
            so.setKolicina(Integer.parseInt(txtKolicina.getText()));
            so.setRoba((Roba) cmbRoba.getSelectedItem());
            ModelTabeleStavke mts = (ModelTabeleStavke) tblStavke.getModel();
            mts.dodaj(so);
        }
        else{
            JOptionPane.showMessageDialog(this, "Greska pri unosu podataka");
        }
    }//GEN-LAST:event_btnDodajActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(tblStavke.getSelectedRow()!=-1){
            ModelTabeleStavke mts = (ModelTabeleStavke) tblStavke.getModel();
            mts.izbrisi(tblStavke.getSelectedRow());
        }
        else{
            JOptionPane.showMessageDialog(this, "Stavka nije izabrana");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            ModelTabeleStavke mts = (ModelTabeleStavke) tblStavke.getModel();
            ArrayList<StavkeOtpremnice> stavke = mts.getLista();
            otpremnica.setStavke(stavke);
            otpremnica.setOdrediste(txtOdrediste.getText());
            ControllerClient.getInstance().updateOtpremnica(otpremnica);
            JOptionPane.showMessageDialog(this, "Otpremnica je sacuvana");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Doslo je do greske pri cuvanju podataka");
            //Logger.getLogger(IzmenaOtpremniceForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JComboBox<String> cmbJedinica;
    private javax.swing.JComboBox cmbRoba;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblKlijent;
    private javax.swing.JTable tblStavke;
    private javax.swing.JTextField txtKolicina;
    private javax.swing.JTextField txtOdrediste;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        try {
            ModelTabeleStavke mts = new ModelTabeleStavke();
            tblStavke.setModel(mts);
            ArrayList<FizickoLice> listaF = ControllerClient.getInstance().getFizickaLica();
            ArrayList<PravnoLice> listaP = ControllerClient.getInstance().getPravnaLica();
            for (PravnoLice pl : listaP) {
                if(pl.getKlijent().getID() == otpremnica.getKlijent().getKlijentID()) lblKlijent.setText(pl.getNaziv());
            }
            for (FizickoLice fl : listaF) {
                if(fl.getKlijent().getID() == otpremnica.getKlijent().getKlijentID()) lblKlijent.setText(fl.getIme() + " " + fl.getPrezime());
            }
            cmbRoba.removeAllItems();
            ArrayList<Roba> listaR = ControllerClient.getInstance().getRoba();
            for (Roba r : listaR) {
                cmbRoba.addItem(r);
            }
            cmbJedinica.removeAllItems();
            cmbJedinica.addItem("kom");
            cmbJedinica.addItem("kg");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska pri ucitavanju podataka");
            this.dispose();
            //Logger.getLogger(KreiranjeOtpremniceForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private boolean provera() {
        char[] kol = txtKolicina.getText().toCharArray();
        for (char c : kol) {
            if(Character.isLetter(c)) return false;
        }
        return true;
    }
}
