/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.otpremnica;

import communication.Request;
import controller.ControllerClient;
import domain.Otpremnica;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import operations.Operations;
import view.components.ModelTabeleOtpremnice;

/**
 *
 * @author milos
 */
public class PretrazivanjeOtpremniceForma extends javax.swing.JDialog {

    /**
     * Creates new form IzmenaOtpremniceForma
     */
    public PretrazivanjeOtpremniceForma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblOtpremnice = new javax.swing.JTable();
        txtOdrediste = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnPrikazi = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblOtpremnice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblOtpremnice);

        jLabel1.setText("Unesite odrediste otpremnice:");

        btnPrikazi.setText("Prikazi");
        btnPrikazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtOdrediste, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(btnPrikazi, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOdrediste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrikazi))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIzmeni)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        ModelTabeleOtpremnice mto = (ModelTabeleOtpremnice) tblOtpremnice.getModel();
        IzmenaOtpremniceForma iof = new IzmenaOtpremniceForma(null, true, mto.getOtpremnica(tblOtpremnice.getSelectedRow()));
        iof.setVisible(true);
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnPrikaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziActionPerformed
        try {
            if(txtOdrediste.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Unesite odrediste");
            }
            else{
                String kriterijum = txtOdrediste.getText();
                ModelTabeleOtpremnice mtp = (ModelTabeleOtpremnice) tblOtpremnice.getModel();
                Request r = new Request();
                r.setOperation(Operations.PRETRAZI_OTPREMNICE);
                r.setArgument(kriterijum);
                ArrayList<Otpremnica> lista = ControllerClient.getInstance().getOtpremnice(r);
                mtp.setLista(lista);
                if(lista.size()==0){
                    JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje otpremnice po zadatoj vrednosti");
                }
            }
            
            
        } catch (Exception ex) {
            Logger.getLogger(PretrazivanjeOtpremniceForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPrikaziActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnPrikazi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOtpremnice;
    private javax.swing.JTextField txtOdrediste;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        try {
            Request r = new Request();
            r.setOperation(Operations.VRATI_OTPREMNICE);
            ArrayList<Otpremnica> listaOtpremnica = ControllerClient.getInstance().getOtpremnice(r);
            System.out.println(listaOtpremnica.size());
            ModelTabeleOtpremnice mto = new ModelTabeleOtpremnice(listaOtpremnica);
            tblOtpremnice.setModel(mto);
            JOptionPane.showMessageDialog(this, "Ucitana je lista otpremnica");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greska pri ucitavanju podataka");
            //Logger.getLogger(PretrazivanjeOtpremniceForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
